### ISSUE TITLE
Use this plugin on Github pages? Getting the data out of the last generated .json file?

### ISSUE THREAD

**Issue by mvaneijgen** [ivantsepp/jekyll-git_metadata#20]
I wanted the show my latest commit hash on my site, so that I can make sure the files are correctly compiled by Github Pages, but running custom Jekyll plugins on there is not an option. Than I saw that there were JSON files created with each commit, so I thought that I could serve the data from there. The only thing I need is creating a static file inside a `_data` folder and have populate the contents with the latest version of the `.json` file inside the `.git-metadata` folder.

Is their a trick I'm missing or is this not that easy?

**Comment by ivantsepp** [comment]
You're absolutely right that Github Pages doesn't allow custom Jekyll plugins. The `.git-metadata` folder is for caching `git` results for this plugin.

I would recommend using https://github.com/jekyll/github-metadata since it's an official plugin and it seems to fit your use case with the `build_revision` attribute!
